apply from:"../featureConfig.build.gradle"

android {

    namespace 'com.hja.feature_home'

    defaultConfig {
        if (rootProject.ext.isModule){
            applicationId "com.hja.feature_home"
        }
    }

}

dependencies {
//    implementation libs.appcompat
//    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    annotationProcessor libs.arouterCompiler
    implementation project(":library_base")
}