if (rootProject.ext.isModule) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'
}

android {
//    namespace 'com.hja.feature_find'
    compileSdk {
        version = release(rootProject.ext.compileSdkVersion)
    }

    defaultConfig {
//        if (rootProject.ext.isModule) {
//            applicationId "com.hja.feature_find"
//        }
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    dataBinding{
        enabled true
    }

    sourceSets {

        main {
            if (rootProject.ext.isModule) {
                //单独运行的模块
                manifest.srcFile 'src/main/alone/AndroidManifest.xml'
            } else {
                //需要合并到app主module
                manifest.srcFile 'src/main/AndroidManifest.xml'
            }
        }

    }
}