plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.hja.video'
    compileSdk {
        version = release(rootProject.ext.compileSdkVersion)
    }

    defaultConfig {
        applicationId "com.hja.video"
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        dataBinding true
    }
}

dependencies {
//    implementation libs.appcompat
//    implementation libs.material

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    annotationProcessor libs.arouterCompiler
    if (rootProject.ext.isModule){
        implementation project(":library_base")
    }else{
        //被集成
        implementation project(":library_base")
        implementation project(":feature_home")
        implementation project(":feature_plaza")
        implementation project(":feature_find")
        implementation project(":feature_user")
    }


}