plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.hja.libbase'
    compileSdk {
        version = release(rootProject.ext.compileSdkVersion)
    }

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        dataBinding true
    }

}

dependencies {
    api libs.appcompat
    api libs.material
    api libs.activity
    api libs.constraintlayout
    api libs.arouter
    api libs.liveData
    api libs.viewModel
    api libs.androidAutoSize

    annotationProcessor libs.arouterCompiler
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}